# Generated by Django 4.1.3 on 2022-11-28 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
